language: python

stages:
  - name: test
    if: type = pull_request OR branch = master
  - name: publish
    if: branch = master AND tag IS present

jobs:
  include:
    - &test
      stage: test
      before_install:
        - pip install poetry
      install:
        - poetry install
      script:
        - mypy
        - pytest -v
      python: 3.5
    - <<: *test
      python: 3.6
    - <<: *test
      python: 3.7
    - <<: *test
      python: 3.8
    - stage: publish
      before_deploy:
        - pip install poetry
      deploy:
        provider: script
        script: poetry publish --build -u __token__ -p $PYPI_TOKEN
